### ISSUE TITLE
Deprecate: flattenImages  causes aesthetic issues on CMS

### ISSUE THREAD

**Issue by sktzoootech** [ivoba/silverstripe-simple-pdf-preview#3]
Hi the following line needs to be replaced:

$img = $img->flattenImages();

with 

$img->setImageAlphaChannel(11);
$img->mergeImageLayers(imagick::LAYERMETHOD_FLATTEN);

Would be nice if you can change it as I use your module on my projects and I use composer to update it. Good job on the module btw.

**Comment by ivoba** [comment]
Done.
fixed in 1.1.0
thx
