### ISSUE TITLE
reserved indicator "%" cannot start a plain scalar error after SS4.7 update

### ISSUE THREAD

**Issue by elkebe** [ivoba/silverstripe-simple-pdf-preview#4]
After updating to SS 4.7 get the following error:

Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: The reserved indicator "%" cannot start a plain scalar; you need to quote the scalar at line 6 (near "generator: %$Ivoba\SilverStripe\SimplePdfPreview\SimplePdfPreviewImagickGenerator")

appears to be in config.yml file

**Comment by elkebe** [comment]
Fixed by adding quotes as in https://github.com/Behat/Behat/issues/1216

config.yml:
generator: ‘%$Ivoba\SilverStripe\SimplePdfPreview\SimplePdfPreviewImagickGenerator’

**Comment by ivoba** [comment]
@elkebe Thanks. Would you make a PR for this fix?

**Comment by ivoba** [comment]
Fixed in 2.0.1
