### ISSUE TITLE
PDF previews only save to default assets folder

### ISSUE THREAD

**Issue by elkebe** [ivoba/silverstripe-simple-pdf-preview#5]
SS4.7.1

Currently in config.yml:
folderToSave: "Uploads"

PDF previews save to top-level assets folder and if folderToSave is changed, no preview is created. Could also just be a documentation error?

**Comment by elkebe** [comment]
Would also be better if default is for preview to be saved into same folder as original pdf file.

**Comment by ivoba** [comment]
@elkebe Can you check if https://github.com/ivoba/silverstripe-simple-pdf-preview/pull/8 fixed this issue?

**Comment by RVXD** [comment]
#9 will fix this.

**Comment by ivoba** [comment]
Fixed in 2.2.0
